### ISSUE TITLE
Create accessible copies of reports and summary tables

### ISSUE THREAD

**Issue by GCDevExchange-CarrefourProgGC** [canada-ca/PCO-Public-Opinion-Research__Recherche-en-opinion-publique--BCP#2]
Value: $9,999.00Closes: Friday, January 12, 2018Location:  Some in-person work required<h2>Opportunity Description</h2><p><span style="font-size: 10.5pt; line-height: 115%; font-family: Verdana, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Currently, the reports and summary tables from historical Privy Council Office&nbsp;public opinion research on the Public Opinion Research Reports website are available to the public in .doc, .docx, .rtf and .xlsx format.&nbsp; Treasury Board of Canada Secretariat&nbsp;requires that these be provided in HTML5 and conform&nbsp;to a minimum of WCAG 2.0 level AA.&nbsp; As such this opportunity will involve converting the reports and summary tables for the consultations listed in the Acceptance Criteria into HTML5/WGCAG 2.0, and providing a method for the Public Opinion Research team to be able to make do these conversions themselves for future consultations.</span></p><h2>Acceptance Criteria</h2><p>1.&nbsp; Provide HTML5/WCAG 2.0 files for the consultations listed in the URLs below:</p>
<p><strong>English:</strong></p>
<ol>
<li style="list-style-type: none;">
<ol start="1" type="1">
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l1 level1 lfo1; tab-stops: list .5in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/index.html">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/index.html</a> </span></li>
<ol start="1" type="1">
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l1 level2 lfo1; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/report.doc">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/report.doc</a> </span></li>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l1 level2 lfo1; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/summary.doc">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/summary.doc</a> </span></li>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l1 level2 lfo1; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/tables-jan_2017.doc">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/tables-jan_2017.doc</a> </span></li>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l1 level2 lfo1; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/tables-feb_2017.doc">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/tables-feb_2017.doc</a> </span></li>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l1 level2 lfo1; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/tables-mar_2017.doc">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/tables-mar_2017.doc</a> </span></li>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l1 level2 lfo1; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/tables-jan_2017-mar_2017.rtf">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/tables-jan_2017-mar_2017.rtf</a> </span></li>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l1 level2 lfo1; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/variable_info-winter_2017.docx">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/variable_info-winter_2017.docx</a></li>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l1 level2 lfo1; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/variable_values-winter_2017.docx">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/variable_values-winter_2017.docx</a></li>
</ol>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l1 level1 lfo1; tab-stops: list .5in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-e/index.html">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-e/index.html</a> &nbsp; </span></li>
<ol start="1" type="1">
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l1 level2 lfo1; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-e/report.docx">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-e/report.docx</a> </span></li>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l1 level2 lfo1; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-e/summary.docx">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-e/summary.docx</a> </span></li>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l1 level2 lfo1; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-e/data.xlsx">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-e/data.xlsx</a></span></li>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l1 level2 lfo1; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-e/variable_information.docx">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-e/variable_information.docx</a></li>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l1 level2 lfo1; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-e/variable_values.docx">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-e/variable_values.docx</a></li>
</ol>
</ol>
<p><strong><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';">&nbsp;French:</span></strong></p>
<ol start="1" type="1">
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l0 level1 lfo2; tab-stops: list .5in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-f/index.html">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-f/index.html</a> </span></li>
<ol start="1" type="1">
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l0 level2 lfo2; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-f/rapport.doc">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-f/rapport.doc</a> </span></li>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l0 level2 lfo2; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-f/sommaire.doc">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-f/sommaire.doc</a> </span></li>
</ol>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l0 level1 lfo2; tab-stops: list .5in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-f/index.html">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-f/index.html</a></span></li>
<ol start="1" type="1">
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l0 level2 lfo2; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-f/rapport.docx">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-f/rapport.docx</a> </span></li>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l0 level2 lfo2; tab-stops: list 1.0in; border: none; mso-padding-alt: 0in 0in 0in 0in;"><span style="font-size: 10.5pt; font-family: 'Verdana','sans-serif';"><a href="http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-f/sommaire.docx">http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/030-16-f/sommaire.docx</a> </span></li>
</ol>
</ol>
</li>
</ol>
<p>2.&nbsp; Provide an easy to use method that the Public Opinion Research team at PCO will use in-house for the conversion of future public opinion research.</p>
<p class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal;">&nbsp;</p><h2>How to Apply</h2><p>Go to the <a href="https://gcdevexchange-carrefourproggc.org/opportunities/opp-create-web-accessible-copies-of-pco-por-reports-and-summary-tables">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Friday, January 12, 2018</b>.</p><p>We plan to assign this opportunity by <b>Friday, January 19, 2018</b> with work to start on <b>Monday, January 22, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>&nbsp;</p>
<ol style="margin-top: 0in;" start="1" type="1">
<li class="MsoNormalCxSpFirst" style="color: #595959; line-height: 230%; mso-list: l0 level1 lfo1;"><span style="font-size: 10.5pt; line-height: 230%;">Confirmation that you are eligible to work in Canada</span></li>
<li class="MsoNormalCxSpMiddle" style="color: #595959; line-height: 230%; mso-list: l0 level1 lfo1;"><span style="font-size: 10.5pt; line-height: 230%;">Confirmation that you can meet all the Acceptance Criteria by February 16, 2017</span></li>
<li class="MsoNormalCxSpMiddle" style="color: #595959; line-height: 230%; mso-list: l0 level1 lfo1;"><span style="font-size: 10.5pt; line-height: 230%;">Your Approach for meeting each of the Acceptance Criteria. <strong>(60 points)</strong></span></li>
<li class="MsoNormalCxSpMiddle" style="color: #595959; line-height: 230%; mso-list: l0 level1 lfo1;"><span style="font-size: 10.5pt; line-height: 230%;">Your Experience working with relevant agile projects and work with HTML 5 - please provide links to your previous work on GitHub or other repositories&nbsp;<strong>(40 points)</strong>.</span></li>
</ol>
<ol start="1" type="1">
<li class="MsoNormal" style="color: #595959; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: 230%; mso-list: l0 level1 lfo1; tab-stops: list .5in;"></li>
</ol>

**Comment by matthewdarwin** [comment]
The link for "how to apply" goes to an invalid location.

**Comment by markwooff** [comment]
Thanks for flagging @matthewdarwin - this has been fixed with https://github.com/canada-ca/devex/pull/43

**Comment by matthewdarwin** [comment]
The linked "GCDevExchange terms and contract" should probably "terms and conditions"?

**Comment by markwooff** [comment]
That's what it's being called elsewhere, makes sense for consistency. Will update as such!
