### ISSUE TITLE
Doc missing OLE file in Appendix B

### ISSUE THREAD

**Issue by steve-h** [canada-ca/PCO-Public-Opinion-Research__Recherche-en-opinion-publique--BCP#7]
http://epe.lac-bac.gc.ca/100/200/301/pwgsc-tpsgc/por-ef/privy_council/2017/081-16-e/report.doc

has an appendix B with a linked embedded file that is missing so it is hard to convert the full document properly.

**Comment by KarenMoorcroft** [comment]
Hi Steve, 
I am able to see and open the embedded file.  It is missing for you?  This is what I see:

![pco_survey_appendixb](https://user-images.githubusercontent.com/34485737/34168248-04dbd6be-e4b2-11e7-9d6d-b9f248f3ced9.PNG)

**Comment by steve-h** [comment]
I see the PCO Survey - English Questionaire.htm icon but it does not open anything for me to see or convert to html on either a mac or pc with the latest Office.
The project implies using this file set as a test and I cannot see how to convert this embedded content if I cannot even see it?
If it is a trick, tnen do you want the icon to show in the html with alt text saying nothing here move along?

**Comment by RachelMuston** [comment]
Hi @steve-h, we are troubleshooting this... the embedded file opens for us unless we are on mobile in which case the link is removed.  For now i have added the file to the repo here:  https://github.com/canada-ca/PCO-Public-Opinion-Research__Recherche-en-opinion-publique--BCP/blob/master/PCO%20Survey%20-%20January%202017.htm 

Thanks for spotting that and apologies!

**Comment by steve-h** [comment]
I opened the word doc and the .htm file is inside the doc binary file but does not show when I download the report.doc.  I can change the hyperlink value on the icon to refer to my own copy of the .htm file that you supplied.  I assume that anyone using the archives report has this problem as well.

I guess this is why publishing .doc files is not accessible; even to skilled technologists :-)

**Comment by steve-h** [comment]
For the record I have [documented the method I used to extract](https://canada-ca.github.io/PCO-Public-Opinion-Research__Recherche-en-opinion-publique--BCP/embeddedcontent.html) these forms of appendices. My initial failure was due to Word on Mac.  I did get a process to work on Word PC.

Closing my own issue.
